### ISSUE TITLE
add support for yum-based systems

### ISSUE THREAD

**Issue by oskapt** [rancher/ansible-playbooks#1]
Add support for yum-based systems like CentOS and RHEL

**Comment by nseyvet** [comment]
Using https://github.com/geerlingguy/ansible-role-docker to install docker, the rest is pretty straightforward.

The following dependencies are needed in yum:

```
- name: install additional dependencies (yum)
  yum: name={{ item }} state=present
  with_items:
    - MySQL-python
    - mysql
  tags: yum

```

maybe I could share some of my mods to make this work with yum and CentOS if it is of interest?
